/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AFormItemRest: typeof import('ant-design-vue/es')['FormItemRest']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    AStyleProvider: typeof import('ant-design-vue/es')['StyleProvider']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    KeySelector: typeof import('./../components/KeySelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VBatch: typeof import('./../components/v-batch.vue')['default']
    VButton: typeof import('./../components/v-button.vue')['default']
    VForm: typeof import('./../components/v-form.vue')['default']
    VIcon: typeof import('./../components/v-icon.vue')['default']
    VItemModal: typeof import('./../components/v-forms/v-item-picker/v-item-modal.vue')['default']
    VItemPicker: typeof import('./../components/v-forms/v-item-picker/v-item-picker.vue')['default']
    VKeySelect: typeof import('./../components/v-key-select.vue')['default']
    VLoad: typeof import('./../components/v-table/v-load.vue')['default']
    VModal: typeof import('./../components/v-table/v-modal.vue')['default']
    VPickerIcon: typeof import('./../components/v-forms/v-picker-icon.vue')['default']
    VPop: typeof import('./../components/v-table/v-pop/v-pop.vue')['default']
    VRadioButton: typeof import('./../components/v-forms/v-radio-button.vue')['default']
    VRangeNumber: typeof import('./../components/v-forms/v-range-number.vue')['default']
    VStatus: typeof import('./../components/v-table/v-status.vue')['default']
    VTable: typeof import('./../components/v-table/v-table.vue')['default']
    VUpload: typeof import('./../components/v-forms/v-upload/v-upload.vue')['default']
  }
}
