// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddApiKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddApiKey'](arg1, arg2, arg3, arg4);
}

export function CreateBundleId(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBundleId'](arg1, arg2, arg3);
}

export function CreateCertificate(arg1, arg2) {
  return window['go']['main']['App']['CreateCertificate'](arg1, arg2);
}

export function CreateDevice(arg1, arg2) {
  return window['go']['main']['App']['CreateDevice'](arg1, arg2);
}

export function CreateProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2, arg3, arg4);
}

export function DeleteApiKey(arg1) {
  return window['go']['main']['App']['DeleteApiKey'](arg1);
}

export function DeleteBundleId(arg1) {
  return window['go']['main']['App']['DeleteBundleId'](arg1);
}

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DownloadCertificate(arg1) {
  return window['go']['main']['App']['DownloadCertificate'](arg1);
}

export function ExportP12(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportP12'](arg1, arg2, arg3);
}

export function GetApiKeys() {
  return window['go']['main']['App']['GetApiKeys']();
}

export function ListApps() {
  return window['go']['main']['App']['ListApps']();
}

export function ListBundleIds() {
  return window['go']['main']['App']['ListBundleIds']();
}

export function ListCertificates() {
  return window['go']['main']['App']['ListCertificates']();
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function RevokeCertificate(arg1) {
  return window['go']['main']['App']['RevokeCertificate'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SetCurrentKey(arg1) {
  return window['go']['main']['App']['SetCurrentKey'](arg1);
}

export function TestAuth() {
  return window['go']['main']['App']['TestAuth']();
}

export function UpdateApiKey(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateApiKey'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadIPA(arg1) {
  return window['go']['main']['App']['UploadIPA'](arg1);
}
