// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddApiKey(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateBundleId(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateCertificate(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateDevice(arg1:string,arg2:string):Promise<string>;

export function CreateProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function DeleteApiKey(arg1:number):Promise<void>;

export function DeleteBundleId(arg1:string):Promise<void>;

export function DeleteDevice(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DownloadCertificate(arg1:string):Promise<string>;

export function DownloadProfile(arg1:string):Promise<string>;

export function ExportCSR(arg1:string):Promise<string>;

export function ExportLocalData():Promise<string>;

export function ExportLocalP12(arg1:string):Promise<string>;

export function ExportP12(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportP12WithOpenSSL(arg1:string):Promise<string>;

export function ExportPEM(arg1:string):Promise<string>;

export function GetApiKeys():Promise<Array<backend.ApiKey>>;

export function ImportLocalData(arg1:string):Promise<void>;

export function ListApps():Promise<string>;

export function ListBundleIds():Promise<string>;

export function ListCertificates():Promise<string>;

export function ListCertificatesWithLocal():Promise<string>;

export function ListDevices():Promise<string>;

export function ListProfiles():Promise<string>;

export function RevokeCertificate(arg1:string):Promise<void>;

export function SaveBase64File(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveTextFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectFile():Promise<string>;

export function SetCurrentKey(arg1:number):Promise<void>;

export function TestAuth():Promise<boolean>;

export function UpdateApiKey(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateCertificatePassword(arg1:string,arg2:string):Promise<string>;

export function UploadIPA(arg1:string):Promise<void>;

export function VerifyP12Password(arg1:string):Promise<string>;
